App:
  server_port: "8080"
  jwt_secret: "local-secret"
  timezone: ""
  debug: true

Databases:
  writer:
    driver: ""
    host: "localhost"
    port: "3306"
    user: "root"
    password: ""
    name: "_local"
    timezone: "UTC"
